export const categories = {
  community: [
    'activities',
    'artists',
    'childcare',
    'classes',
    'events',
    'general',
    'groups',
    'local news',
    'lost+found',
    'missed connections',
    'musicians',
    'pets',
    'politics',
    'rants & raves',
    'rideshare',
    'volunteers',
  ],
  housing: [
    'apartments / housing',
    'housing swap',
    'housing wanted',
    'office / commercial',
    'parking / storage',
    'real estate for sale',
    'rooms / shared',
    'rooms wanted',
    'sublets / temporary',
    'vacation rentals',
  ],
  jobs: [
    'accounting+finance',
    'admin / office',
    'arch / engineering',
    'art / media / design',
    'biotech / science',
    'business / mgmt',
    'customer service',
    'education',
    'food / bev / hosp',
    'general labor',
    'government',
    'human resources',
    'internet engineers',
    'legal / paralegal',
    'manufacturing',
    'marketing / pr / ad',
    'medical / health',
    'nonprofit sector',
    'real estate',
    'retail / wholesale',
    'sales / biz dev',
    'salon / spa / fitness',
    'security',
    'skilled trade / craft',
    'software / qa / dba',
    'systems / network',
    'technical support',
    'transport',
    'tv / film / video',
    'web / info design',
    'writing / editing',
  ],
  forSale: [
    'antiques',
    'appliances',
    'arts+crafts',
    'atv/utv/sno',
    'auto parts',
    'baby+kids',
    'barter',
    'beauty+hlth',
    'bikes',
    'boats',
    'books',
    'business',
    'cars+trucks',
    'cds/dvd/vhs',
    'cell phones',
    'clothes+acc',
    'collectibles',
    'computers',
    'electronics',
    'farm+garden',
    'free',
    'furniture',
    'garage sale',
    'general',
    'heavy equip',
    'household',
    'jewelry',
    'materials',
    'motorcycles',
    'music instr',
    'photo+video',
  ],
  services: [
    'automotive',
    'beauty',
    'cell/mobile',
    'computer',
    'creative',
    'cycle',
    'event',
    'farm+garden',
    'financial',
    'household',
    'labor/move',
    'legal',
    'lessons',
    'marine',
    'pet',
    'real estate',
    'skilled trade',
    'small biz ads',
    'therapeutic',
    'travel/vac',
    'write/ed/tr8',
  ],
  gigs: [
    'computer',
    'creative',
    'crew',
    'domestic',
    'event',
    'labor',
    'talent',
    'writing',
  ],
};
